grades/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'grades'
urlpatterns = [

	# Default folders: registration/*.*, accounts/login/*.*
	url(r'^$', views.BaseView.as_view(), name = 'base'),
	url(r'^login/$', auth_views.login, name = 'login'),	# Set with LOGIN_URL in settings.py
	url(r'^logout/$', auth_views.logout, name = 'logout'),	# TODO: Create template
	
    url(r'^index/$', login_required(views.IndexView.as_view()), name = 'index'),
	url(r'^courses/(?P<slug>[-\w\d]+)/$', login_required(views.CourseView.as_view()), name = 'course'),
	url(r'^g/(?P<slug>[-\w\d]+)/$', login_required(views.EditGradeView.as_view()), name = 'edit-grade'),
	url(r'^add-course/$', login_required(views.AddCourseView.as_view()), name = 'add-course'),
	url(r'^courses/(?P<slug>[-\w\d]+)/add-grade/$', login_required(views.AddGradeView.as_view()), name = 'add-grade'),
	url(r'^g/(?P<slug>[-\w\d]+)/delete/$', login_required(views.DeleteGradeView.as_view()), name = 'delete-grade'),
]

gradesproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^grades/', include('grades.urls'))
]

grades/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

import uuid


class Course(models.Model):
	student = models.ForeignKey(User)
	course_id = models.CharField('Course ID', max_length = 16, unique = True)
	name = models.CharField(max_length = 128)
	slug = models.SlugField(default = 'TEST')
	professor_firstname = models.CharField('Professor\'s first name', max_length = 64)
	professor_lastname = models.CharField('Professor\'s last name', max_length = 128)
	
	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		temp_id = self.course_id
		temp_id.replace(' ', '')
		self.slug = slugify(temp_id).upper()
		super(Course, self).save(*args, **kwargs)

	def get_grade(self):
		points = 0
		total = 0
		if not self.grade_set.all():
			return 0
		
		for grade in self.grade_set.all():
			points += grade.points_received
			total += grade.total_points
		
		return round((points / total) * 100, 1)


class Grade(models.Model):
	course = models.ForeignKey(Course, on_delete = models.CASCADE)
	ASSIGNMENT_CHOICES = (
		(0, 'Homework'),
		(1, 'Quiz'),
		(2, 'Exam'),
		(3, 'Project'),
		(4, 'Other'),
	)
	
	name = models.CharField(max_length = 64)
	slug = models.SlugField()
	type = models.IntegerField(choices = ASSIGNMENT_CHOICES, default = 0)
	date = models.DateField(auto_now = False, auto_now_add = False, null = True, blank = True)
	total_points = models.IntegerField()
	points_received = models.IntegerField()
	
	def __str__(self):
		return '{0} - {1}'.format(self.course.name, self.name)

	def save(self, *args, **kwargs):
		exists = Grade.objects.filter(id = self.id)
		if not exists:
			uid = uuid.uuid4()
			self.slug = slugify(str(uid))
		super(Grade, self).save(*args, **kwargs)

	def get_grade(self):
		return round((self.points_received / self.total_points) * 100, 1)

grades/forms.py
from django import forms
from django.utils import timezone
from django.contrib.auth.models import User

from .models import Course, Grade


class GradeForm(forms.ModelForm):
	
	ASSIGNMENT_CHOICES = (
		(0, 'Homework'),
		(1, 'Quiz'),
		(2, 'Exam'),
		(3, 'Project'),
		(4, 'Other'),
		(5, 'Extra Credit'),
	)
	
	date = forms.DateField(
		widget = forms.SelectDateWidget(
			empty_label = ('Year', 'Month', 'Day'),
			years = range(2000, timezone.now().year + 1)
		)
	)
	
	class Meta:
		model = Grade
		fields = ['course', 'date', 'name', 'type', 'total_points', 'points_received']


class CourseForm(forms.ModelForm):
	
	class Meta:
		model = Course
		fields = ['course_id', 'name', 'professor_firstname', 'professor_lastname']


class UserForm(forms.ModelForm):
	
	password = forms.CharField(widget = forms.PasswordInput)
	
	class Meta:
		model = User
		fields = ['username', 'email', 'password']

grades/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.views import generic

from .models import Course, Grade
from .forms import GradeForm, CourseForm, UserForm


class BaseView(generic.View):

	# If the user is logged in, take him/her to the index page. If not, redirect to the login page.
	def get(self, request):
		if request.user.is_authenticated and request.user.is_active:
			return redirect('grades:index')
		else:
			return redirect('grades:login')


class IndexView(generic.ListView):
	template_name = 'grades/index.html'
	context_object_name = 'course_list'
	
	def get_queryset(self):
		student = self.request.user
		return student.course_set.all()


class CourseView(generic.DetailView):
	model = Course
	template_name = 'grades/course.html'
	
	def get_context_data(self, *args, **kwargs):
		context = super(CourseView, self).get_context_data(*args, **kwargs)
		course = self.get_object()
		all_grades = course.grade_set.all().order_by('date')
		context['grade_list'] = all_grades
		
		assignment_types = ['homeworks', 'quizzes', 'exams', 'projects', 'other']
		for e in enumerate(assignment_types):
			grades = all_grades.filter(type = e[0])	# Retrieves grades by type number
			context[e[1]] = grades

		return context


class EditGradeView(generic.UpdateView):
	model = Grade
	form_class = GradeForm
	template_name = 'grades/edit-grade.html'
	
	def get_success_url(self):
		return reverse('grades:course', args = [self.get_object().course.slug])


class AddGradeView(generic.CreateView):
	model = Grade
	form_class = GradeForm
	template_name = 'grades/edit-grade.html'
	
	def get_success_url(self):
		return reverse('grades:index')


class DeleteGradeView(generic.DeleteView):
	model = Grade
	
	def get_success_url(self):
		return reverse('grades:index')

class AddCourseView(generic.CreateView):
	model = Course
	form_class = CourseForm
	template_name = 'grades/edit-course.html'
	
	def form_valid(self, form):
		form.instance.student = self.request.user
		return super(AddCourseView, self).form_valid(form)	# Must return!

	def get_success_url(self):
		return reverse('grades:index')


class UserFormView(generic.View):
	form_class = UserForm
	template_name = 'grades/signup-form.html'
	
	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, { 'form': form })
		
	def post(self, request):
		form = self.form_class(request.POST)
		self.form_valid(form)
		super(UserFormView, self).post(request)
		
	def form_valid(self, form):
		user = form.save(commit = False)
		username = form.cleaned_data['username']
		password = form.cleaned_data['password']
		
		user.set_password(password)	# Uses the hash value
		user.save()
		
		user_auth = authenticate(username = username, password = password)
		
		if user_auth is not None:
			if user_auth.is_active:
				login(request, user)
				return redirect('grades:index')

grades/templates/grades/base.html
{% load static %}

<html>
<head>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<link href="https://fonts.googleapis.com/css?family=Kalam" rel="stylesheet">

<link rel = "stylesheet" href = "{% static 'grades/style.css' %}">



<title>{% block title %}{% endblock title %} - GradeView</title>
</head>

<body>

<nav class = "navbar navbar-default">
		<div class = "container-fluid">
		
		<!-- Logo -->
		<div class = "navbar-header">
			<!-- In case of mobile, display a navigation button. -->
			<button type = "button" class = "navbar-toggle" data-toggle = "collapse" data-target = "#topNavBar">
				<span class = "glyphicon glyphicon-menu-hamburger"></span>
			</button>
			<a class = "navbar-brand logo" href = "{% url 'grades:index' %}">GradeView</a>
		</div>
		
		<!-- Items -->
		<div id = "topNavBar" class = "collapse navbar-collapse">
			<ul class = "nav navbar-nav">
				<li class = "">
					<a href = "#">
						<span class = "glyphicon glyphicon-calendar" aria-hidden = "true"></span>&nbsp;
						My Courses
					</a>
				</li>
				
				<li class = "">
					<a href = "{% url 'grades:add-course' %}">
						<span class = "glyphicon glyphicon-plus" aria-hidden = "true"></span>&nbsp;
						Add Course
					</a>
				</li>
			</ul>
			
			
			<ul class = "nav navbar-nav navbar-right">
				<li class = "">
					<a href = "#">
						<span class = "glyphicon glyphicon-user"></span>&nbsp;
						My Profile
					</a>
				</li>
			</ul>
			
		</div>
		
	</nav>

<h2>{% block header %}{% endblock %}</h2>

{% block content %}
{% endblock %}
</body>

</html>

grades/templates/grades/course.html
{% extends 'grades/base.html' %}
{% block title %}{{ course.name }}{% endblock %}
{% block header %}{{ course.name }}{% endblock %}


{% block content %}
	<table class = "table table-hover">
		<thead>
		<tr>
			<th>Date</th>
			<th>Assignment</th>
			<th>Points/Total</th>
			<th>Score</th>
			<th><a href= "{% url 'grades:add-grade' course.slug %}">Add grade</a></th>
		</tr>
		<thead>
		
		<tbody>
		<tr>Homework:</tr>
		{% for homework in homeworks %}
			<tr>
				<th>{{ homework.date }}</th>
				<th>{{ homework.name }}</th>
				<th>{{ homework.points_received }}/{{ homework.total_points }}</th>
				<th>{{ homework.get_grade }}%</th>
				<th><a href = "{% url 'grades:edit-grade' homework.slug %}"><span class = "glyphicon glyphicon-pencil"></span></a></th>
				<th><a href = "{% url 'grades:delete-grade' homework.slug %}"><span class = "glyphicon glyphicon-trash"></span></a></th>
			</tr>
		{% endfor %}

		{% for quiz in quizzes %}
			<tr>Quizzes:</tr>
			<tr>
				<th>{{ quiz.date }}</th>
				<th>{{ quiz.name }}</th>
				<th>{{ quiz.points_received }}/{{ quiz.total_points }}</th>
				<th>{{ quiz.get_grade }}%</th>
				<th><a href = "{% url 'grades:edit-grade' quiz.slug %}"><span class = "glyphicon glyphicon-pencil"></span></a></th>
				<th><a href = "{% url 'grades:delete-grade' quiz.slug %}"><span class = "glyphicon glyphicon-trash"></span></a></th>
			</tr>
		{% endfor %}

		{% for exam in exams %}
			<tr>Exams:</tr>
			<tr>
				<th>{{ exam.date }}</th>
				<th>{{ exam.name }}</th>
				<th>{{ exam.points_received }}/{{ exam.total_points }}</th>
				<th>{{ exam.get_grade }}%</th>
				<th><a href = "{% url 'grades:edit-grade' exam.slug %}"><span class = "glyphicon glyphicon-pencil"></span></a></th>
				<th><a href = "{% url 'grades:delete-grade' exam.slug %}"><span class = "glyphicon glyphicon-trash"></span></a></th>
			</tr>
		{% endfor %}

		{% for project in projects %}
			<tr>Projects:</tr>
			<tr>
				<th>{{ project.date }}</th>
				<th>{{ project.name }}</th>
				<th>{{ project.points_received }}/{{ project.total_points }}</th>
				<th>{{ project.get_grade }}%</th>
				<th><a href = "{% url 'grades:edit-grade' project.slug %}"><span class = "glyphicon glyphicon-pencil"></span></a></th>
				<th><a href = "{% url 'grades:delete-grade' project.slug %}"><span class = "glyphicon glyphicon-trash"></span></a></th>
			</tr>
		{% endfor %}

		{% for o in other %}
			<tr>Other assignments:</tr>
			<tr>
				<th>{{ o.date }}</th>
				<th>{{ o.name }}</th>
				<th>{{ o.points_received }}/{{ o.total_points }}</th>
				<th>{{ o.get_grade }}%</th>
				<th><a href = "{% url 'grades:edit-grade' o.slug %}"><span class = "glyphicon glyphicon-pencil"></span></a></th>
				<th><a href = "{% url 'grades:delete-grade' o.slug %}"><span class = "glyphicon glyphicon-trash"></span></a></th>
			</tr>
		{% endfor %}
		</tbody>
	</table>
{% endblock content %}

grades/templates/grades/edit-course.html
{% extends 'grades/base.html' %}
{% block title %}Editing {{ grade.name }}{% endblock %}
{% block header %}{{ grade.name }}{% endblock %}

{% block content %}

	<form class = "form-horizontal" action = "" method = "POST" enctype = "multipart/form-data">
	{% csrf_token %}
	{% for field in form %}
		<h4>{{ field.label }}</h4>
		<p>{{ field }}</p>
	{% endfor %}
	
	<div class = "form-group">
		<div class = "col-sm-offset-2 col-sm-10">
			<button type = "submit" class = "btn btn-success">Submit</button>
		</div>
	</div>
	</form>

{% endblock content %}

grades/templates/grades/edit-grade.html
{% extends 'grades/base.html' %}
{% block title %}Editing {{ grade.name }}{% endblock %}
{% block header %}{{ grade.name }}{% endblock %}

{% block content %}

	<form class = "form-horizontal" action = "" method = "POST" enctype = "multipart/form-data">
	{% csrf_token %}
		<p>Course: {{ form.course }}</p>
		<p>Date: {{ form.date }}</p>
		<p>Type: {{ form.type }}</p>
		<p>Name: {{ form.name }}</p>
		<p>Points/Total: {{ form.points_received }}/{{ form.total_points }}</p>
	
	<div class = "form-group">
		<div class = "col-sm-offset-2 col-sm-10">
			<button type = "submit" class = "btn btn-success">Submit</button>
		</div>
	</div>
	</form>

{% endblock content %}

grades/templates/grades/grade_confirm_delete.html
{% extends 'grades/base.html' %}

{% block title %}Delete Grade {{ grade.name }}{% endblock %}

{% block header %}{{ grade.name }}{% endblock %}

{% block content %}

	<form action = "" method= "POST">
	{% csrf_token %}
		<p>Are you sure you want to delete "{{ grade.name }}"?</p>
		<input type = "submit" value = "Confirm"/>
	</form>

{% endblock content %}

grades/templates/grades/index.html
{% extends 'grades/base.html' %}
{% block title %}Home{% endblock %}
{% block header %}Courses{% endblock %}


{% block content %}
	<ul>
	{% for course in course_list %}
		<li><a href = "{% url 'grades:course' course.course_id %}">{{ course }} - {{ course.get_grade }}%</a></li>
	{% endfor %}
	</ul>
{% endblock content %}